// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OeptJUgXcMUQhKydJHlRB-2uDRw3TwQ',
    appId: '1:873421946575:web:d4b0e7a38dddb9862201ba',
    messagingSenderId: '873421946575',
    projectId: 'mumbaifinal-54b26',
    authDomain: 'mumbaifinal-54b26.firebaseapp.com',
    storageBucket: 'mumbaifinal-54b26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWcjUsjpxwbgRGlTE0yd3X5sKqp0Wpzw',
    appId: '1:873421946575:android:04e1c7f9b2dbb2d52201ba',
    messagingSenderId: '873421946575',
    projectId: 'mumbaifinal-54b26',
    storageBucket: 'mumbaifinal-54b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TT0GhmhJkH8MR12dU_7XlNdjfb1h2xw',
    appId: '1:873421946575:ios:1c7ce53588c39d9a2201ba',
    messagingSenderId: '873421946575',
    projectId: 'mumbaifinal-54b26',
    storageBucket: 'mumbaifinal-54b26.appspot.com',
    iosBundleId: 'com.example.mumbaihacksfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TT0GhmhJkH8MR12dU_7XlNdjfb1h2xw',
    appId: '1:873421946575:ios:1c7ce53588c39d9a2201ba',
    messagingSenderId: '873421946575',
    projectId: 'mumbaifinal-54b26',
    storageBucket: 'mumbaifinal-54b26.appspot.com',
    iosBundleId: 'com.example.mumbaihacksfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4OeptJUgXcMUQhKydJHlRB-2uDRw3TwQ',
    appId: '1:873421946575:web:48cac96143b4929e2201ba',
    messagingSenderId: '873421946575',
    projectId: 'mumbaifinal-54b26',
    authDomain: 'mumbaifinal-54b26.firebaseapp.com',
    storageBucket: 'mumbaifinal-54b26.appspot.com',
  );
}
